models/Message.php
<?php

namespace app\models;

use app\modules\user\models\Voting;
use Yii;
use yii\helpers\Html;
use yii\web\UploadedFile;

/**
 * This is the model class for table "message".
 *
 * @property integer $id
 * @property string $text
 * @property integer $task_id
 * @property integer $user_id
 * @property integer $admin_id
 * @property string $data
 * @property string $path_first
 * @property string $path_second
 * @property string $path_third
 * @property string $path_fourth
 * @property integer $voting
 * @property boolean $is_readed
 */
class Message extends \yii\db\ActiveRecord
{

    /**
     * @var UploadedFile[]
     */
    public $imageFiles;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'message';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['text'], 'string'],
            [['text', 'task_id'], 'required', 'message' => 'Это поле обязательно!'],
            [['task_id', 'user_id', 'admin_id', 'voting'], 'integer'],
            [['data'], 'safe'],

            [['data'], 'date', 'format' => 'php:Y-m-d H:i:s'],
            [['data'], 'default', 'value' => date('Y-m-d H:i:s')],

            ['is_readed', 'default', 'value' => false],

            [['imageFiles'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg', 'maxFiles' => 4],

            [['path_first', 'path_second', 'path_third', 'path_fourth'], 'string', 'max' => 50],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'text' => 'Сообщение',
            'task_id' => 'Task ID',
            'user_id' => 'User ID',
            'admin_id' => 'Admin ID',
            'data' => 'Дата',
            'imageFiles' => 'Нажмите чтобы загрузить фото в формате png или jpg',
            'path_first' => 'Path First',
            'path_second' => 'Path Second',
            'path_third' => 'Path Third',
            'path_fourth' => 'Path Fourth',
            'voting' => 'Поставьте галочку, если загружаете коллажи для голосования',
            'is_readed' => 'Прочитано или нет',
        ];
    }

    public function messageUserToDB(Message $newMessage, $id)
    {
        $newMessage->task_id = $id;
        if ($newMessage->validate()) {
            $newMessage->text = Html::encode($this->text);
            $newMessage->user_id = Yii::$app->user->getId();
            $newMessage->admin_id = Yii::$app->user->identity['parent_id'];
            //TODO: logic
            $newMessage->save();
            return true;
        }
        return false;
    }

    public function upload()
    {
        //TODO: photos current
        if ($this->imageFiles != null) {
            $newMessage = Message::findOne(['id' => $this->id]);
            $newMessage->voting = $this->voting;

            $i = 1;
            foreach ($this->imageFiles as $file) {
                switch ($i):
                    case 1:
                        $newMessage->path_first = 'user' . Yii::$app->user->identity->getId() . $this->id . $i . "." . $file->extension;
                        $file->saveAs('images/photos/' . $newMessage->path_first);
                        break;
                    case 2:
                        $newMessage->path_second = 'user' . Yii::$app->user->identity->getId() . $this->id . $i . "." . $file->extension;
                        $file->saveAs('images/photos/' . $newMessage->path_second);
                        break;
                    case 3:
                        $newMessage->path_third = 'user' . Yii::$app->user->identity->getId() . $this->id . $i . "." . $file->extension;
                        $file->saveAs('images/photos/' . $newMessage->path_third);
                        break;
                    case 4:
                        $newMessage->path_fourth = 'user' . Yii::$app->user->identity->getId() . $this->id . $i . "." . $file->extension;
                        $file->saveAs('images/photos/' . $newMessage->path_fourth);
                        break;
                endswitch;
                ++$i;
            }
            $newMessage->update();
            if ($this->voting) {
                $pastVoting = Voting::findOne(['user_id' => $newMessage->user_id]);
                if (isset($pastVoting)) {
                    $pastVoting->photoDo = $newMessage->path_first;
                    $pastVoting->photoPosle = $newMessage->path_second;
                    $pastVoting->update();
                    return true;
                } else {
                    return false;
                }
            }
            return true;
        } else {
            return false;
        }
    }

    //TODO: PHOTOS DEPRECATED
    public function messageAdminToDB(Message $newMessage, $id, $user_id)
    {
        if ($this->validate()) {
            $newMessage->text = $this->text;
            $newMessage->task_id = $id;
            $newMessage->user_id = $user_id;
            $newMessage->admin_id = 0;
            $newMessage->save();
            return true;
        }
        return false;
    }

    //TODO: PHOTOS DEPRECATED
//    public function upload()
//    {
//            if (isset($check)) {
//                foreach ($this->imageFiles as $file) {
//                    switch ($i):
//                        case 1:
//                            unlink('images/photos/' . $check->path_first);
//                            $check->path_first = 'user' . Yii::$app->user->identity->getId() . $i . "." . $file->extension;
//                            break;
//                        case 2:
//                            if ($check->path_second != null) {
//                                unlink('images/photos/' . $check->path_second);
//                            }
//                            $check->path_second = 'user' . Yii::$app->user->identity->getId() . $i . "." . $file->extension;
//                            break;
//                        case 3:
//                            if ($check->path_third != null) {
//                                unlink('images/photos/' . $check->path_third);
//                            }
//                            $check->path_third = 'user' . Yii::$app->user->identity->getId() . $i . "." . $file->extension;
//                            break;
//                        case 4:
//                            if ($check->path_fourth != null) {
//                                unlink('images/photos/' . $check->path_fourth);
//                            }
//                            $check->path_fourth = 'user' . Yii::$app->user->identity->getId() . $i . "." . $file->extension;
//                            break;
//                    endswitch;
//                    $file->saveAs('images/photos/user' . Yii::$app->user->identity->getId() . $i . "." . $file->extension);
//                    ++$i;
//                }
//                $check->update();
//                return true;
//            }
//        return false;
//    }
}

controllers/MessageController.php
<?php
/**
 * Created by PhpStorm.
 * User: ayder
 * Date: 8/19/17
 * Time: 6:27 PM
 */

namespace app\controllers;

use app\models\CaptchaForm;
use app\models\Mark;
use app\models\Message;
use app\models\Notification;
use app\modules\user\models\Answer;
use app\modules\user\models\Task;
use app\modules\user\models\User;
use app\modules\user\models\Voting;
use Yii;
use yii\data\Pagination;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\HttpException;
use yii\web\UploadedFile;

/**
 * Class MessageController
 * @package app\modules\user\controllers
 * Actions for messaging between admins and users
 */
class MessageController extends AppController
{
    public $layout = 'user';

    /**
     * tasks for users
     * and list of users for admins
     * @return $this|string|HttpException
     */
    public function actionIndex()
    {
        $this->setMeta('Суперсушка');
        if (Yii::$app->user->isGuest) {
            return Yii::$app->response->redirect(['/user/auth/login']);
        }
        if (!Yii::$app->user->isGuest) {

            return $this->render('index');
        }
        return new HttpException(401);
    }

    public function actionDelete($id = false)
    {
        $this->setMeta('Суперсушка');
        if (Yii::$app->user->isGuest) {
            return $this->redirect('/user/auth/logout');
        }
        $this->setMeta('Суперсушка');
        if (!Yii::$app->user->isGuest) {

            if (isset($id)) {
                $answer = Answer::findOne(['id' => $id]);
                $answer->is_readed = 1;
                $answer->update();
                $this->redirect(['/user/help/feedback']);
            }
            return new HttpException(401);
        }
    }


    public
    function actionAjaxMarks()
    {
        if (Yii::$app->request->isAjax) {
            $marks = Mark::find()->where(['user_id' => Yii::$app->user->getId()])->asArray()->all();
//                return date("H:i:s");
            $result = json_encode($marks);
//            echo $tasks;
            return $result;
        }
    }

    public
    function actionAjaxTasks($week)
    {
        if (Yii::$app->request->isAjax) {
            $tasks = Task::find()->where(['week' => $week])->asArray()->all();
//                return date("H:i:s");
            $result = json_encode($tasks);
//            echo $tasks;
            return $result;
        }
    }

    /**
     * task_content for user and admin
     * @return $this|string|HttpException
     */
    public
    function actionTasks($week = false)
    {
        $this->setMeta('Суперсушка');

        if (Yii::$app->user->isGuest) {
            return Yii::$app->response->redirect(['/user/user/auth_error']);
        }

        if (!Yii::$app->user->isGuest) {

            //$id = Yii::$app->user->getId();

            if (isset($week) && $week == null) {
                $week = 1;
                $tasks = Task::find()->where(['week' => $week])->all();
                if (!isset($tasks))
                    return $this->render('tasks', compact('week'));
                return $this->render('tasks', compact('tasks', 'week'));
            } elseif (isset($week)) {
                $tasks = Task::find()->where(['week' => $week])->all();
                if (!isset($tasks))
                    return $this->render('tasks', compact('week'));
                return $this->render('tasks', compact('tasks', 'week'));
            }

//            return $this->render('tasks');
        }
        return new HttpException(401);

    }

    public
    function actionAjax()
    {
        if (Yii::$app->request->isAjax) {
            $data = Yii::$app->request->post();
            $message = explode(":", $data['message']);
            if ($message != null || $message != '') {
                $task_id = explode(":", $data['task_id']);
                $message = $message[0];
                $task_id = $task_id [0];
                //my code here
                $newMessage = new Message();

                $newMessage->text = Html::encode($message);
                $newMessage->user_id = Yii::$app->user->getId();
                $newMessage->task_id = $task_id;
                $newMessage->admin_id = Yii::$app->user->identity['parent_id'];

                \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                if ($newMessage->validate()) {
                    $newMessage->save();
                    return $message;
                }
            }
            if ($data['message'] == null || $data['message'] == '')
                return 'error!! empty message -' . $message;
        }
    }

    public
    function actionCurrentTask($task_id = false, $admin_id = false)
    {
        $this->setMeta('Суперсушка');
        if (Yii::$app->user->isGuest) {
            return $this->redirect('/user/auth/logout');
        }
        if (!Yii::$app->user->isGuest) {

            if (!isset($admin_id) || $admin_id == null)
                $admin_id = Yii::$app->user->identity['parent_id'];
            $this->setMeta('Суперсушка');
            $task = Task::find()->where(['id' => $task_id])->one();
            $admin = User::find()->where(['id' => $admin_id])->one();

            $message = new Message();
            //chance using
            $voting = Voting::findOne(['user_id' => Yii::$app->user->getId()]);
            //
            if ($message->load(Yii::$app->request->post())) {
                $message->imageFiles = UploadedFile::getInstances($message, 'imageFiles');

                if ($message->messageUserToDB($message, $task_id)) {
                    if ($message->upload())
                        return $this->refresh();

                    //notification
                    $notification = new Notification();
                    $notification->task_id = $task_id;
                    $notification->type = 'messageAdmin';
                    //user id
                    $notification->user_id = Yii::$app->user->getId();
                    $notification->admin_id = $admin->id;
                    $notification->seen = 0;
                    //date
                    date_default_timezone_set('Etc/GMT-3');
                    $notification->created_at = date('Y-m-d H:i:s');
                    $notification->flashed = 0;
                    //user id
                    $notification->admin_name = $admin->name;
                    if ($notification->validate())
                        $notification->save();
                    //notification
                    return $this->refresh();
                } else {
                    return $this->render('current-task', compact('task', 'admin', 'message', 'voting'));
                }
            }

            if (isset($voting) && $voting->load(Yii::$app->request->post())) {
                return $this->immuneChanging($voting, $task, $admin, $message);
            }

            return $this->render('current-task', compact('task', 'admin', 'message', 'voting'));
        }
        return new HttpException(401);
    }

    private
    function findAnswer($id)
    {
        return Answer::find()->where(['id' => $id])->one();
    }

    public
    function actionResults()
    {
        $this->setMeta('Суперсушка');

        if (Yii::$app->user->isGuest) {
            return Yii::$app->response->redirect(['/user/user/auth_error']);
        }

        if (!Yii::$app->user->isGuest) {
            $voting = Voting::findOne(['user_id' => Yii::$app->user->getId()]);
            return $this->render('results', compact('voting'));
        }
        return new HttpException(401);

    }

    public
    function actionVoting()
    {
        $this->setMeta('Суперсушка');

        if (Yii::$app->user->isGuest) {
            return Yii::$app->response->redirect(['/user/auth/login']);
        }

        if (!Yii::$app->user->isGuest) {

            return $this->render('voting');
        }
        return new HttpException(401);

    }

    public
    function actionVotingSecond()
    {
        $this->setMeta('Суперсушка');

        if (Yii::$app->user->isGuest) {
            return Yii::$app->response->redirect(['/user/auth/login']);
        }

        if (!Yii::$app->user->isGuest) {
            return $this->render('voting-second');
        }
        return new HttpException(401);

    }

    public
    function actionVotingThird()
    {
        $this->setMeta('Суперсушка');

        if (Yii::$app->user->isGuest) {
            return Yii::$app->response->redirect(['/user/auth/login']);
        }

        if (!Yii::$app->user->isGuest) {
            return $this->render('voting-third');
        }
        return new HttpException(401);

    }

    /**
     * @param $voting
     * @param $task
     * @param $admin
     * @param $message
     * @return string|\yii\web\Response
     */
    private
    function immuneChanging(Voting $voting, Task $task, $admin, $message)
    {
        if ($voting->changeChance && $voting->chance == 2) {
            $voting->chance -= 1;
            $voting->task_id = $task->id;
            $voting->update();
            $user = User::findOne(['id' => Yii::$app->user->getId()]);
            $user->role_id = 2;
            $user->update();
            Yii::$app->session->setFlash('successImmune');
            return $this->refresh();
        } else {
            Yii::$app->session->setFlash('errorImmune');
            return $this->render('current-task', compact('task', 'admin', 'message', 'voting'));
        }
    }


    public
    function actionCurrent()
    {
        $this->setMeta('Сообщения', 'СуперСушка', 'СуперСушка');
        $messages = Message::find()
            ->where(['user_id' => Yii::$app->user->getId()])
            ->all();
        $admin = User::findOne(['id' => Yii::$app->user->identity['parent_id']]);

        $newMessage = new Message();

        if ($newMessage->load(Yii::$app->request->post())) {

views/message/index.php
<?php

use app\modules\user\models\Answer;
use yii\captcha\Captcha;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

$marks = Answer::find()->where(['user_id' => Yii::$app->user->getId()])->all();
//debug($userQuestion);
?>
<!--file for viewing all user questions cause i won little css using-->
<div class="main_admin_view_all">
    <p align="center"
       style="font-family: 'Times New Roman',serif;font-size: 24px;color: #000;width: 750px;margin-left: auto;margin-right: auto;margin-top: 25px;">
        Здесь выводятся ответы на вопросы в форме
        <a href="<?= Url::to('/user/help/feedback') ?>">
            <strong>
                обратной связи
            </strong>.
        </a>
    </p>

    <?php if (isset($marks)): ?>
        <?php foreach ($marks

                       as $answer): ?>
            <li class="list-group-item " style="margin-left: auto;
    margin-right: auto;width:550px;font-size: 17px;font-family: Cambria,serif;margin-top: 25px;color:#000">
                <strong>Имя: </strong><?= Html::encode($answer->name) ?>
                <br>
                <hr>
                <strong>Тема вопроса: </strong><?= Html::encode($answer->theme) ?>
                <hr>
                <strong>Ответ: </strong>
                <br>
                <?= Html::encode($answer->text) ?>
                <br>

                <?= Html::a('Закрыть вопрос', Url::to(['/message/delete', 'id' => $answer->id]),
                    ['style' => 'color:red']) ?>
            </li>
        <?php endforeach; ?>

    <?php endif; ?>

    <?php
    if (isset($marks)): ?>
        <li class="list-group-item " style="margin-left: auto;
    margin-right: auto;width:550px;font-size: 17px;font-family: Cambria,serif;margin-top: 25px;color:#000">
            У вас больше нет сообщений!
        </li>
    <?php endif; ?>

</div>

views/message/results.php
<?php
/**
 * supersushka - results.php
 *
 * Initial version by: Tom
 * Initial created on: 05.10.2017 5:31
 */

use app\models\Mark;
use app\modules\user\models\Task;
use app\modules\user\models\User;
use app\modules\user\models\Voting;
use yii\helpers\Html;
use yii\helpers\Url;

$marks = Mark::find()->where(['user_id' => Yii::$app->user->getId()])->all();
//$iUserVoting = Voting::findOne(['user_id' => Yii::$app->user->getId()]);

?>

<div class="user_container well" style="border-radius: 10px;">

    <div class="row" style="min-height: 650px;">

        <h4 align="center" id="title" class="title"><?= Html::encode("Результаты заданий:") ?></h4>
        <?php if (Yii::$app->user->identity['role_id'] == 4): ?>
            <div class="list-group-item border-green border_radius_margin">
                <h3 align="center" class="text-post">
                    <?= Html::encode("Можете не волноваться!") ?>
                    <br>
                    <?= Html::encode("У Вас ПОЛНЫЙ иммунитет - 
            поэтому задания вас не касаются!") ?>
                </h3>
            </div>
        <?php endif; ?>


        <p align="center">
            <strong>
                **<?= Html::img('@web/images/exclamation_point.png', ['width' => 40, 'height' => 40,
                    'style' => 'margin-right:10px;']) ?> - обязательное задание!
            </strong>
            <br>
            <strong>
                **<?= Html::img('@web/images/happy.svg', ['width' => 40, 'height' => 40,
                    'style' => 'margin-right:15px;']) ?> - задание выполнено!
            </strong>
            <br>
            <strong>
                **<?= Html::img('@web/images/sad.svg', ['width' => 40, 'height' => 40,
                    'style' => 'margin-right:15px;']) ?> - задание не выполнено!
            </strong>

        </p>

        <?php if (isset($marks)): ?>
            <?php foreach ($marks
                           as $mark):
                $task = Task::findOne(['id' => $mark->task_id]); ?>
                <!--            border-radius: 15px;-->
                <div class="list-group-item task-results" style="height: 59px;">

                    <?= Html::encode($task->title) ?>
                    <?php
                    $originalDate = strtotime($task->date);
                    $Month_r = array(
                        "01" => "января",
                        "02" => "февраля",
                        "03" => "марта",
                        "04" => "апреля",
                        "05" => "мая",
                        "06" => "июня",
                        "07" => "июля",
                        "08" => "августа",
                        "09" => "сентября",
                        "10" => "октября",
                        "11" => "ноября",
                        "12" => "декабря");
                    $now_month = date('m', $originalDate); // месяц на eng
                    $rus_month = $Month_r[$now_month];

                    $newDate = date("- d ", $originalDate) . $rus_month
                        . date(" Y ", $originalDate);
                    echo Html::encode($newDate) ?>

                    <?php
                        if ($task->status) {
                            echo Html::img('@web/images/exclamation_point.png', ['width' => 40, 'height' => 40, 'float' => 'none',
                                'align' => 'right']);
                        }
                        if ($mark->status == 1): ?>
                            <?= Html::img('@web/images/happy.svg', ['width' => 40, 'height' => 40,
                                'float' => 'none', 'align' => 'right']) ?>
                        <?php endif; ?>

                    <?php if ($mark->status == 0): ?>

                        <?= Html::img('@web/images/sad.svg', ['width' => 40, 'height' => 40, 'float' => 'none',
                            'align' => 'right']) ?>
                        <?php if ($voting->changeChance && ($voting->task_id == $mark->task_id)): ?>
                            <strong style="color: red;font-size: 18px;">
                                <?= Html::encode("Можете не волноваться! Здесь Вы использовали иммунитет!") ?>
                            </strong>
                            <?= Html::img('@web/images/happy.svg', ['width' => 40, 'height' => 40, 'align' => 'right',
                                'style' => 'position:absolute']) ?>

                        <?php endif; ?>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>

        <?php endif; ?>

        <?php
        if ($marks == null): ?>
            <div class="list-group-item flash text-post">
                У вас пока что нет заданий!
            </div>
        <?php endif; ?>

        <div class="list-group-item flash text-post border_margin">
            Результаты голосования:
        </div>


        <?php //TODO: Voting button?>
        <div class="faq-create" align='center' style='position: absolute;float: inherit;'>
            <?php $patch = \app\modules\user\models\Patches::findOne(['status' => 1]);
            if (isset($patch) && $patch->voting_level == 1):
                echo Html::a('Голосование 1 тур итоги', ['/message/voting'],
                    ['class' => 'btn btn-warning',
                        'style' => 'font-size: 15px;margin-left: auto;
    margin-right: auto;'
                    ]);
            elseif (isset($patch) && $patch->voting_level == 2):
                echo Html::a('Голосование 2 тур итоги', ['/message/voting-second'],
                    ['class' => 'btn btn-danger',
                        'style' => 'font-size: 15px;margin-left: auto;
    margin-right: auto;'
                    ]);
            elseif (isset($patch) && $patch->voting_level == 3):
                echo Html::a('Голосование 3 тур итоги', ['/message/voting-third'], [
                    'class' => 'btn btn-success',
                    'style' => 'font-size: 15px;margin-left: auto;
    margin-right: auto;'
                ]);
            endif;
            ?>
        </div>
    </div>
</div>

views/message/tasks.php
<?php

use app\modules\user\models\Task;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\widgets\LinkPager;

?>

<script>
    var user_week = "<?=$week?>";
    var tasks_tokenCsrf = "<?=Yii::$app->request->getCsrfToken()?>";
    var tasks_admin_id = "<?=Yii::$app->user->identity['parent_id']?>";
</script>

<div class="user_container well post-font" style="border-radius: 10px;">

    <h1 align="center" id="title" class="title"><?= Html::encode('#СуперСушка17') ?></h1>
    <?php if (isset($week) && $week != null): ?>
        <?php if ($week == 1): ?>
            <ul class="nav nav-pills week">
                <h3 align="left" id="title">Задания распределяются по неделям:</h3>

                <li role="presentation" class="active list-group-item "><a
                            href="<?= Url::to(['/message/tasks/', 'week' => 1]) ?>">1</a></li>
                <li role="presentation" class=" list-group-item "><a
                            href="<?= Url::to(['/message/tasks/', 'week' => 2]) ?>">2</a></li>
                <li role="presentation" class=" list-group-item "><a
                            href="<?= Url::to(['/message/tasks/', 'week' => 3]) ?>">3</a></li>
                <li role="presentation" class="list-group-item "><a
                            href="<?= Url::to(['/message/tasks/', 'week' => 4]) ?>">4</a></li>

            </ul>
        <?php endif; ?>
        <?php if ($week == 2): ?>
            <ul class="nav nav-pills week">
                <h3 align="left"><strong>Задания распределяются по неделям:</strong></h3>

                <li role="presentation" class="list-group-item "><a
                            href="<?= Url::to(['/message/tasks/', 'week' => 1]) ?>">1</a></li>
                <li role="presentation" class="active list-group-item "><a
                            href="<?= Url::to(['/message/tasks/', 'week' => 2]) ?>">2</a></li>
                <li role="presentation" class="list-group-item "><a
                            href="<?= Url::to(['/message/tasks/', 'week' => 3]) ?>">3</a></li>
                <li role="presentation" class="list-group-item "><a
                            href="<?= Url::to(['/message/tasks/', 'week' => 4]) ?>">4</a></li>

            </ul>
        <?php endif; ?>

        <?php if ($week == 3): ?>
            <ul class="nav nav-pills week">
                <h3 align="left"><strong>Задания распределяются по неделям:</strong></h3>

                <li role="presentation" class="list-group-item "><a
                            href="<?= Url::to(['/message/tasks/', 'week' => 1]) ?>">1</a></li>
                <li role="presentation" class=" list-group-item "><a
                            href="<?= Url::to(['/message/tasks/', 'week' => 2]) ?>">2</a></li>
                <li role="presentation" class="active list-group-item "><a
                            href="<?= Url::to(['/message/tasks/', 'week' => 3]) ?>">3</a></li>
                <li role="presentation" class="list-group-item "><a
                            href="<?= Url::to(['/message/tasks/', 'week' => 4]) ?>">4</a></li>

            </ul>
        <?php endif; ?>

        <?php if ($week == 4): ?>
            <ul class="nav nav-pills week">
                <h3 align="left"><strong>Задания распределяются по неделям:</strong></h3>

                <li role="presentation" class="list-group-item "><a
                            href="<?= Url::to(['/message/tasks/', 'week' => 1]) ?>">1</a></li>
                <li role="presentation" class=" list-group-item "><a
                            href="<?= Url::to(['/message/tasks/', 'week' => 2]) ?>">2</a></li>
                <li role="presentation" class=" list-group-item "><a
                            href="<?= Url::to(['/message/tasks/', 'week' => 3]) ?>">3</a></li>
                <li role="presentation" class="active list-group-item "><a
                            href="<?= Url::to(['/message/tasks/', 'week' => 4]) ?>">4</a></li>

            </ul>
        <?php endif; ?>
    <?php endif; ?>
    <?php if (!isset($week) || $week == null): ?>
        <ul class="nav nav-pills week">
            <h3 align="left"><strong>Задания распределяются по неделям:</strong></h3>

            <li role="presentation" class="active list-group-item "><a
                        href="<?= Url::to(['/message/tasks/', 'week' => 1]) ?>">1</a></li>
            <li role="presentation" class=" list-group-item "><a
                        href="<?= Url::to(['/message/tasks/', 'week' => 2]) ?>">2</a></li>
            <li role="presentation" class="list-group-item "><a
                        href="<?= Url::to(['/message/tasks/', 'week' => 3]) ?>">3</a></li>
            <li role="presentation" class="list-group-item "><a
                        href="<?= Url::to(['/message/tasks/', 'week' => 4]) ?>">4</a></li>
        </ul>
        <?php
        $tasks = Task::find()->where(['week' => 1])->all();
    endif;
    ?>

    <p align="center">
        <strong>
            **<?= Html::img('@web/images/exclamation_point.png', ['width' => 40, 'height' => 40,
                'style' => 'margin-right:10px;']) ?> - обязательное задание!
        </strong>
        <br>
        <strong>
            **<?= Html::img('@web/images/happy.svg', ['width' => 40, 'height' => 40,
                'style' => 'margin-right:15px;']) ?> - задание выполнено!
        </strong>
        <br>
        <strong>
            **<?= Html::img('@web/images/sad.svg', ['width' => 40, 'height' => 40,
                'style' => 'margin-right:15px;']) ?> - задание не выполнено!
        </strong>

    </p>

    <?php if($tasks==null):?>
        <h4 align='center' id='title' class='title'>
            Пока что на этой неделе нет заданий.
        </h4>
    <?php endif;?>
    <div id="content" >

    </div>

</div>