controllers/MessageController.php
<?php
/**
 * Created by PhpStorm.
 * User: ayder
 * Date: 8/19/17
 * Time: 6:27 PM
 */

namespace app\controllers;

use app\models\CaptchaForm;
use app\models\Mark;
use app\models\Message;
use app\models\Notification;
use app\modules\user\models\Answer;
use app\modules\user\models\Task;
use app\modules\user\models\User;
use app\modules\user\models\Voting;
use Yii;
use yii\data\Pagination;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\HttpException;
use yii\web\UploadedFile;

/**
 * Class MessageController
 * @package app\modules\user\controllers
 * Actions for messaging between admins and users
 */
class MessageController extends AppController
{
    public $layout = 'user';

    /**
     * tasks for users
     * and list of users for admins
     * @return $this|string|HttpException
     */
    public function actionIndex()
    {
        $this->setMeta('Суперсушка');
        if (Yii::$app->user->isGuest) {
            return Yii::$app->response->redirect(['/user/auth/login']);
        }
        if (!Yii::$app->user->isGuest) {

            return $this->render('index');
        }
        return new HttpException(401);
    }

    public function actionDelete($id = false)
    {
        $this->setMeta('Суперсушка');
        if (Yii::$app->user->isGuest) {
            return $this->redirect('/user/auth/logout');
        }
        $this->setMeta('Суперсушка');
        if (!Yii::$app->user->isGuest) {

            if (isset($id)) {
                $answer = Answer::findOne(['id' => $id]);
                $answer->is_readed = 1;
                $answer->update();
                $this->redirect(['/user/help/feedback']);
            }
            return new HttpException(401);
        }
    }


    public
    function actionAjaxMarks()
    {
        if (Yii::$app->request->isAjax) {
            $marks = Mark::find()->where(['user_id' => Yii::$app->user->getId()])->asArray()->all();
//                return date("H:i:s");
            $result = json_encode($marks);
//            echo $tasks;
            return $result;
        }
    }

    public
    function actionAjaxTasks($week)
    {
        if (Yii::$app->request->isAjax) {
            $tasks = Task::find()->where(['week' => $week])->asArray()->all();
//                return date("H:i:s");
            $result = json_encode($tasks);
//            echo $tasks;
            return $result;
        }
    }

    /**
     * task_content for user and admin
     * @return $this|string|HttpException
     */
    public
    function actionTasks($week = false)
    {
        $this->setMeta('Суперсушка');

        if (Yii::$app->user->isGuest) {
            return Yii::$app->response->redirect(['/user/user/auth_error']);
        }

        if (!Yii::$app->user->isGuest) {

            //$id = Yii::$app->user->getId();

            if (isset($week) && $week == null) {
                $week = 1;
                $tasks = Task::find()->where(['week' => $week])->all();
                if (!isset($tasks))
                    return $this->render('tasks', compact('week'));
                return $this->render('tasks', compact('tasks', 'week'));
            } elseif (isset($week)) {
                $tasks = Task::find()->where(['week' => $week])->all();
                if (!isset($tasks))
                    return $this->render('tasks', compact('week'));
                return $this->render('tasks', compact('tasks', 'week'));
            }

//            return $this->render('tasks');
        }
        return new HttpException(401);

    }

    public
    function actionAjax()
    {
        if (Yii::$app->request->isAjax) {
            $data = Yii::$app->request->post();
            $message = explode(":", $data['message']);
            if ($message != null || $message != '') {
                $task_id = explode(":", $data['task_id']);
                $message = $message[0];
                $task_id = $task_id [0];
                //my code here
                $newMessage = new Message();

                $newMessage->text = Html::encode($message);
                $newMessage->user_id = Yii::$app->user->getId();
                $newMessage->task_id = $task_id;
                $newMessage->admin_id = Yii::$app->user->identity['parent_id'];

                \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                if ($newMessage->validate()) {
                    $newMessage->save();
                    return $message;
                }
            }
            if ($data['message'] == null || $data['message'] == '')
                return 'error!! empty message -' . $message;
        }
    }

    public
    function actionCurrentTask($task_id = false, $admin_id = false)
    {
        $this->setMeta('Суперсушка');
        if (Yii::$app->user->isGuest) {
            return $this->redirect('/user/auth/logout');
        }
        if (!Yii::$app->user->isGuest) {

            if (!isset($admin_id) || $admin_id == null)
                $admin_id = Yii::$app->user->identity['parent_id'];
            $this->setMeta('Суперсушка');
            $task = Task::find()->where(['id' => $task_id])->one();
            $admin = User::find()->where(['id' => $admin_id])->one();

            $message = new Message();
            //chance using
            $voting = Voting::findOne(['user_id' => Yii::$app->user->getId()]);
            //
            if ($message->load(Yii::$app->request->post())) {
                $message->imageFiles = UploadedFile::getInstances($message, 'imageFiles');

                if ($message->messageUserToDB($message, $task_id)) {
                    if ($message->upload())
                        return $this->refresh();

                    //notification
                    $notification = new Notification();
                    $notification->task_id = $task_id;
                    $notification->type = 'messageAdmin';
                    //user id
                    $notification->user_id = Yii::$app->user->getId();
                    $notification->admin_id = $admin->id;
                    $notification->seen = 0;
                    //date
                    date_default_timezone_set('Etc/GMT-3');
                    $notification->created_at = date('Y-m-d H:i:s');
                    $notification->flashed = 0;
                    //user id
                    $notification->admin_name = $admin->name;
                    if ($notification->validate())
                        $notification->save();
                    //notification
                    return $this->refresh();
                } else {
                    return $this->render('current-task', compact('task', 'admin', 'message', 'voting'));
                }
            }

            if (isset($voting) && $voting->load(Yii::$app->request->post())) {
                return $this->immuneChanging($voting, $task, $admin, $message);
            }

            return $this->render('current-task', compact('task', 'admin', 'message', 'voting'));
        }
        return new HttpException(401);
    }

    private
    function findAnswer($id)
    {
        return Answer::find()->where(['id' => $id])->one();
    }

    public
    function actionResults()
    {
        $this->setMeta('Суперсушка');

        if (Yii::$app->user->isGuest) {
            return Yii::$app->response->redirect(['/user/user/auth_error']);
        }

        if (!Yii::$app->user->isGuest) {
            $voting = Voting::findOne(['user_id' => Yii::$app->user->getId()]);
            return $this->render('results', compact('voting'));
        }
        return new HttpException(401);

    }

    public
    function actionVoting()
    {
        $this->setMeta('Суперсушка');

        if (Yii::$app->user->isGuest) {
            return Yii::$app->response->redirect(['/user/auth/login']);
        }

        if (!Yii::$app->user->isGuest) {

            return $this->render('voting');
        }
        return new HttpException(401);

    }

    public
    function actionVotingSecond()
    {
        $this->setMeta('Суперсушка');

        if (Yii::$app->user->isGuest) {
            return Yii::$app->response->redirect(['/user/auth/login']);
        }

        if (!Yii::$app->user->isGuest) {
            return $this->render('voting-second');
        }
        return new HttpException(401);

    }

    public
    function actionVotingThird()
    {
        $this->setMeta('Суперсушка');

        if (Yii::$app->user->isGuest) {
            return Yii::$app->response->redirect(['/user/auth/login']);
        }

        if (!Yii::$app->user->isGuest) {
            return $this->render('voting-third');
        }
        return new HttpException(401);

    }

    /**
     * @param $voting
     * @param $task
     * @param $admin
     * @param $message
     * @return string|\yii\web\Response
     */
    private
    function immuneChanging(Voting $voting, Task $task, $admin, $message)
    {
        if ($voting->changeChance && $voting->chance == 2) {
            $voting->chance -= 1;
            $voting->task_id = $task->id;
            $voting->update();
            $user = User::findOne(['id' => Yii::$app->user->getId()]);
            $user->role_id = 2;
            $user->update();
            Yii::$app->session->setFlash('successImmune');
            return $this->refresh();
        } else {
            Yii::$app->session->setFlash('errorImmune');
            return $this->render('current-task', compact('task', 'admin', 'message', 'voting'));
        }
    }


    public
    function actionCurrent()
    {
        $this->setMeta('Сообщения', 'СуперСушка', 'СуперСушка');
        $messages = Message::find()
            ->where(['user_id' => Yii::$app->user->getId()])
            ->all();
        $admin = User::findOne(['id' => Yii::$app->user->identity['parent_id']]);

        $newMessage = new Message();

        if ($newMessage->load(Yii::$app->request->post())) {

views/uzer/search.php
<?php
/**
 * supersushka - search.php
 *
 * Initial version by: Tom
 * Initial created on: 23.09.2017 20:50
 */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

?>

<div class="user_container well" style="border-radius: 10px;">

    <ul class="nav nav-tabs nav-justified news">
        <li><a href="<?= Url::to('/uzer/news') ?>"><strong>Новости</strong></a></li>
        <li><a href="<?= Url::to('/uzer/followers') ?>"><strong>Подписки</strong></a></li>
        <li class="active"><a href="#"><strong>Поиск</strong></a></li>
    </ul>

    <div class="list-group-item search-form post-font">

        <?php $form = ActiveForm::begin(); ?>
        <?= $form->field($search, 'name')->textInput(['placeholder' => 'Кого вы ищете?']) ?>
        <?= $form->field($search, 'surname')->textInput(['placeholder' => 'Какая у него/неё фамилия?']) ?>
        <p align="center">
            <?= Html::a('Искать', ['search'], [
                'class' => 'btn btn-success',
                'style' => 'font-size: 16px;',
                'data' => [
                    'method' => 'post',
                ],
            ]) ?>
        </p>
        <?php $form = ActiveForm::end(); ?>
    </div>


    <?php if (Yii::$app->session->hasFlash('successSearch')): ?>
        <div class="alert alert-success alert-dismissible flash border_radius" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span>
            </button>
            <strong>Поиск осуществлён!</strong>
        </div>
    <?php endif; ?>

    <?php if (Yii::$app->session->hasFlash('errorSearch')): ?>
        <div class="alert alert-danger alert-dismissible flash border_radius" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span>
            </button>
            <strong> Ошибка! Пользователя с заданными именем и фамилией нет в системе.</strong>
        </div>
    <?php endif; ?>

    <?php if (isset($result) & $result!=null) : ?>
            <a href="<?= Url::to(['/uzer/view', 'user_id' => $result->id]) ?>">

                <div class=" well search-form-result">

                    <?= $result->name ?>
                    <?= $result->surname ?>
                </div>
            </a>

    <?php endif; ?>

</div>

views/uzer/update-page.php
<?php
/**
 * supersushka - update-page.php
 *
 * Initial version by: Tom
 * Initial created on: 11.11.2017 18:50
 */

use app\modules\user\models\Task;
use yii\helpers\Html;

if (isset($week))
    $tasks = Task::find()->where(['week' => $week])->all();
if (!isset($week))
    $tasks = Task::find()->where(['week' => 1])->all();

?>

<div class="task_container user-tasks">


    <?php if (isset($week)): ?>
        <?php if ($week == 1): ?>
            <ul class="nav nav-pills week">
                <h3 align="left"><strong>Задания распределяются по неделям:</strong></h3>

                <li role="presentation" class="active list-group-item "><a
                        href="<?= Url::to(['/message/tasks/', 'week' => 1]) ?>">1</a></li>
                <li role="presentation" class=" list-group-item "><a
                        href="<?= Url::to(['/message/tasks/', 'week' => 2]) ?>">2</a></li>
                <li role="presentation" class=" list-group-item "><a
                        href="<?= Url::to(['/message/tasks/', 'week' => 3]) ?>">3</a></li>
                <li role="presentation" class="list-group-item "><a
                        href="<?= Url::to(['/message/tasks/', 'week' => 4]) ?>">4</a></li>

            </ul>
        <?php endif; ?>
        <?php if ($week == 2): ?>
            <ul class="nav nav-pills week">
                <h3 align="left"><strong>Задания распределяются по неделям:</strong></h3>

                <li role="presentation" class="list-group-item "><a
                        href="<?= Url::to(['/message/tasks/', 'week' => 1]) ?>">1</a></li>
                <li role="presentation" class="active list-group-item "><a
                        href="<?= Url::to(['/message/tasks/', 'week' => 2]) ?>">2</a></li>
                <li role="presentation" class="list-group-item "><a
                        href="<?= Url::to(['/message/tasks/', 'week' => 3]) ?>">3</a></li>
                <li role="presentation" class="list-group-item "><a
                        href="<?= Url::to(['/message/tasks/', 'week' => 4]) ?>">4</a></li>

            </ul>
        <?php endif; ?>

        <?php if ($week == 3): ?>
            <ul class="nav nav-pills week">
                <h3 align="left"><strong>Задания распределяются по неделям:</strong></h3>

                <li role="presentation" class="list-group-item "><a
                        href="<?= Url::to(['/message/tasks/', 'week' => 1]) ?>">1</a></li>
                <li role="presentation" class=" list-group-item "><a
                        href="<?= Url::to(['/message/tasks/', 'week' => 2]) ?>">2</a></li>
                <li role="presentation" class="active list-group-item "><a
                        href="<?= Url::to(['/message/tasks/', 'week' => 3]) ?>">3</a></li>
                <li role="presentation" class="list-group-item "><a
                        href="<?= Url::to(['/message/tasks/', 'week' => 4]) ?>">4</a></li>

            </ul>
        <?php endif; ?>

        <?php if ($week == 4): ?>
            <ul class="nav nav-pills week">
                <h3 align="left"><strong>Задания распределяются по неделям:</strong></h3>

                <li role="presentation" class="list-group-item "><a
                        href="<?= Url::to(['/message/tasks/', 'week' => 1]) ?>">1</a></li>
                <li role="presentation" class=" list-group-item "><a
                        href="<?= Url::to(['/message/tasks/', 'week' => 2]) ?>">2</a></li>
                <li role="presentation" class=" list-group-item "><a
                        href="<?= Url::to(['/message/tasks/', 'week' => 3]) ?>">3</a></li>
                <li role="presentation" class="active list-group-item "><a
                        href="<?= Url::to(['/message/tasks/', 'week' => 4]) ?>">4</a></li>

            </ul>
        <?php endif; ?>
    <?php endif; ?>
    <?php if (!isset($week) || $week == null): ?>
        <ul class="nav nav-pills week">
            <h3 align="left"><strong>Задания распределяются по неделям:</strong></h3>

            <li role="presentation" class="active list-group-item "><a
                    href="<?= Url::to(['/message/tasks/', 'week' => 1]) ?>">1</a></li>
            <li role="presentation" class=" list-group-item "><a
                    href="<?= Url::to(['/message/tasks/', 'week' => 2]) ?>">2</a></li>
            <li role="presentation" class="list-group-item "><a
                    href="<?= Url::to(['/message/tasks/', 'week' => 3]) ?>">3</a></li>
            <li role="presentation" class="list-group-item "><a
                    href="<?= Url::to(['/message/tasks/', 'week' => 4]) ?>">4</a></li>
        </ul>
        <?php
        $tasks = Task::find()->where(['week' => 1])->all();
    endif;
    ?>

    <?php if (isset($tasks)): ?>
        <?php
        $today = date("Y-m-d");
        foreach ($tasks as $task) :
            $result = ($task->date <= $today); //$result == true
            if ($result):?>
                <a href="<?= Url::to(['/message/current-task', 'task_id' => $task->id,
                    'admin_id' => Yii::$app->user->identity['parent_id']]) ?>">
                    <div class="well">
                        <?= Html::encode($task->title) . " " . Html::encode($task->date) ?>
                        <?php $taskMark = \app\models\Mark::findOne(['user_id' => Yii::$app->user->getId(), 'task_id' => $task->id]) ?>
                        <?php if (isset($taskMark)): ?>
                            <?php if ($taskMark->status == 1): ?>
                                <?= Html::img('@web/images/happy.svg', ['width' => 50, 'height' => 50, 'style' => 'border-radius:15px;',
                                    'align' => 'right']) ?>
                            <?php endif; ?>

                            <?php if ($taskMark->status == 0): ?>
                                <?= Html::img('@web/images/sad.svg', ['width' => 45, 'height' => 45,
                                    'align' => 'right']) ?>
                            <?php endif; ?>
                        <?php endif; ?>

                        <?php if ($task->status == 1): ?>
                            <?= Html::img('@web/images/exclamation_point.png', ['width' => 35, 'height' => 35,
                                'style' => 'margin-right:15px;', 'align' => 'right']) ?>
                        <?php endif; ?>
                    </div>
                </a>
                <?php
            endif;
        endforeach; ?>

        <p align="center">
            <strong>
                **<?= Html::img('@web/images/exclamation_point.png', ['width' => 40, 'height' => 40,
                    'style' => 'margin-right:10px;']) ?> - обязательное задание!
            </strong>
            <br>
            <strong>
                **<?= Html::img('@web/images/happy.svg', ['width' => 40, 'height' => 40,
                    'style' => 'margin-right:15px;']) ?> - задание выполнено!
            </strong>
            <br>
            <strong>
                **<?= Html::img('@web/images/sad.svg', ['width' => 40, 'height' => 40,
                    'style' => 'margin-right:15px;']) ?> - задание не выполнено!
            </strong>

            <?=Html::submitButton('Update', ['id'=>'updatePage'])?>
        </p>
    <?php endif; ?>

</div>

views/uzer/update.php
<?php

use app\models\Comment;
use app\models\Follow;
use app\models\Post;
use app\models\PostUpdateForm;
use app\modules\user\models\Image;
use app\modules\user\models\ProfileUpdateForm;
use app\modules\user\models\User;
use app\modules\user\models\UserQuestion;
use yii\bootstrap\Modal;
use yii\data\Pagination;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\widgets\LinkPager;

?>

<div class="user_container">

    <div class="list-group-item update-post" align="center">

        <?php

        $postForm = ActiveForm::begin();

        echo $postForm->field($modelPost, 'content')->textarea(['placeholder' => 'Что ты хочешь добавить?', 'rows' => 5,
            'style' => 'width:90%;border-radius:15px;'])->label('Изменить пост');

        echo Html::submitButton('Сохранить', [
            'class' => 'btn btn-success bun',
            'style' => 'margin-top:20px;',
            'data' => [
                'method' => 'post',
            ],
        ]);

        if (isset($view)):
            switch ($view):
                case  'view':
                    echo Html::a('Назад', Url::to('/uzer/view'), ['class' => 'btn btn-warning bun',
                        'style' => 'margin-top:20px;',]);
                    break;
                case  'news':
                    echo Html::a('Назад', Url::to('/uzer/news'), ['class' => 'btn btn-warning bun',
                        'style' => 'margin-top:20px;',]);
                    break;
                case  'followers':
                    echo Html::a('Назад', Url::to('/uzer/followers'), ['class' => 'btn btn-warning bun',
                        'style' => 'margin-top:20px;',]);
                    break;
            endswitch;
        endif;
        if (!isset($view))
            echo Html::a('Назад', Url::to('/uzer/view'),['class' => 'btn btn-warning bun',
                'style' => 'margin-top:20px;',]);
        $postForm = ActiveForm::end();

        ?>
    </div>

</div>